CLIBS= 		-lm -lglut -lGL -lGLU -lX11 # 2014
#CPATHS=	-L/usr/X11R6/lib -I/usr/X11R6/include # 2011
CPATHS=		-I/usr/include -L/usr/lib # 2014
CFLAGS=		$(CPATHS)$(CLIBS)


kickhamG3:	kickhamG3.cpp
		g++ kickhamG3.cpp -o kickhamG3 $(CFLAGS)

clean:
		rm *.o
