CLIBS= 		-lm -lglut -lGL -lGLU -lX11 # 2014
#CPATHS=	-L/usr/X11R6/lib -I/usr/X11R6/include # 2011
CPATHS=		-I/usr/include -L/usr/lib # 2014
CFLAGS=		$(CPATHS)$(CLIBS)


perspect1:	perspect1.cpp
		g++ perspect1.cpp -o perspect1 $(CFLAGS)

clean:
		rm *.o
